[setup]
  token = ""

[commands]
  # The command prefixes, that each command must start with
  prefixes = ["!", "?"]

  # Configuration for the Tag command
  [commands.tag]

    [commands.tag.modify]
      # A list with roles whose users are allowed to modify tags.
      allowed-roles= [  ]


[database]
  connection-url = "jdbc:sqlite:db.sqlite"

# JDK
[[javadoc]]
  base-url = "https://docs.oracle.com/en/java/javase/12/docs/api"
  all-classes-appendix = "/allclasses-index.html"

# JavaFx
[[javadoc]]
  base-url = "https://openjfx.io/javadoc/12/"
  all-classes-appendix = "/allclasses.html"

[messages]
  [messages.error]
    self-destruct = true
    destruction-delay = 5
  [messages.information]
    self-destruct = true
    destruction-delay = 5
  [messages.success]
    self-destruct = true
    destruction-delay = 5
  [messages.none]
    self-destruct = true
    destruction-delay = 5

[permissions]
  # The admin, probably
  id_328235363099213824 = ["tag.create", "tag.delete"]